name: QuantumROM Tools

on:
  workflow_dispatch:
    inputs:
      SUPPORT_MODEL:
        description: "==== MAKE ROM FOR ==== Device Model"
        required: true
        default: "SM-A225F"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository.
      uses: actions/checkout@v3

    - name: Installing required packages.
      run: |
        chmod +x ./scripts/install_packages.sh
        sudo bash ./scripts/install_packages.sh

    - name: D-loading_extracting ${{ github.event.inputs.SUPPORT_MODEL }} firmware.
      run: |
        chmod +x ./QuantumROM/Devices/${{ github.event.inputs.SUPPORT_MODEL }}/${{ github.event.inputs.SUPPORT_MODEL }}.sh
        sudo bash ./QuantumROM/Devices/${{ github.event.inputs.SUPPORT_MODEL }}/${{ github.event.inputs.SUPPORT_MODEL }}.sh
