name: QuantumROM Tools

on:
  workflow_dispatch:
    inputs:
      DEVICE_MODEL:
        description: "Enter the DEVICE_MODEL."
        required: true
        default: "SM-A225F"
      CSC:
        description: "Enter the CSC (Country Specific Code)"
        required: true
        default: "CSC_CODE"
      IMEI:
        description: "Enter the device IMEI number"
        required: true
        default: "123456789012345"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository.
      uses: actions/checkout@v3

    - name: Display captured inputs (for debugging)
      run: |
        echo "DEVICE_MODEL: ${{ github.event.inputs.DEVICE_MODEL }}"
        echo "CSC: ${{ github.event.inputs.CSC }}"
        echo "IMEI: ${{ github.event.inputs.IMEI }}"
        
    - name: Installing required packages.
      run: |
        chmod +x ./scripts/install_packages.sh
        sudo bash ./scripts/install_packages.sh

    - name: Downloading and extracting ${{ github.event.inputs.DEVICE_MODEL }} firmware.
      run: |
        chmod +x ./scripts/download_firmware.sh
        sudo bash ./scripts/download_firmware.sh ${{ GITHUB.EVENT.INPUTS.DEVICE_MODEL }} ${{ github.event.inputs.CSC }} ${{ github.event.inputs.IMEI }}

    - name: Run IMG Pack cmd
      run: |
        chmod +x ./bin/make_ext4fs
        chmod +x ./scripts/pack_ext4.sh
        bash ./scripts/pack_ext4.sh "$(pwd)/${fw_download}/${MODEL}" "$(pwd)/${BIN_DIR}" "$(pwd)/${OUT_DIR}"

